version: "2"
issues:
  max-issues-per-linter: 0
  max-same-issues: 3
  new: false
  fix: true
  uniq-by-line: true
  whole-files: false
linters:
  default: all
  settings:
    depguard:
      rules:
        main:
          allow:
            - $gostd
            - github.com/codecrafters-io/bittorrent-starter-go/
formatters:
  # Enable specific formatter.
  # Default: [] (uses standard Go formatting)
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
  settings:
    golines:
      max-len: 80
      shorten-comments: true
      reformat-tags: false
    gofumpt:
      # Choose whether to use the extra rules.
      # Default: false
      extra-rules: true
    gofmt:
      rewrite-rules:
        - pattern: "interface{}"
          replacement: "any"

    # goimports:
    #   # A list of prefixes, which, if set, checks import paths
    #   # with the given prefixes are grouped after 3rd-party packages.
    #   # Default: []
    #   local-prefixes:
    #     - github.com/grzadr/refscaler-service
